name: 'Shopify Locale Sync'
description: 'Sync Shopify Theme Locale JSON files with a GitHub Repository'
author: 'Matthew Fournier'
inputs:
  store:
    required: true
    description: 'Store'

  theme:
    required: true
    description: 'Target Theme ID to sync with GitHub Repository'

  working-directory:
    required: false
    description:
      'Working Directory, root of Shopify Theme, defaults to current directory'
runs:
  main: 'dist/index.js'
  using: 'node20'
